name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Core
      run: dotnet build GameCore.Core --no-restore -c Release
      
    - name: Test Core
      run: dotnet test GameCore.Tests --filter "FullyQualifiedName~GameCore.Core" -c Release
      
    - name: Pack
      run: dotnet pack GameCore.Core -c Release -o artifacts
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: artifacts/*.nupkg
        
    # 发布包到NuGet
    - name: Publish to NuGet
      if: github.event_name == 'release'
      run: |
        foreach($file in Get-ChildItem -Path artifacts/*.nupkg) {
          dotnet nuget push $file --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        }